// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * FlutterPlugin1MyClass:
 *
 */

G_DECLARE_FINAL_TYPE(FlutterPlugin1MyClass, flutter_plugin1_my_class, FLUTTER_PLUGIN1, MY_CLASS, GObject)

/**
 * flutter_plugin1_my_class_new:
 * int_list: field in this object.
 * int_list_length: length of @int_list.
 *
 * Creates a new #MyClass object.
 *
 * Returns: a new #FlutterPlugin1MyClass
 */
FlutterPlugin1MyClass* flutter_plugin1_my_class_new(const uint8_t* int_list, size_t int_list_length);

/**
 * flutter_plugin1_my_class_get_int_list
 * @object: a #FlutterPlugin1MyClass.
 * @length: location to write the length of this value.
 *
 * Gets the value of the intList field of @object.
 *
 * Returns: the field value.
 */
const uint8_t* flutter_plugin1_my_class_get_int_list(FlutterPlugin1MyClass* object, size_t* length);

G_DECLARE_FINAL_TYPE(FlutterPlugin1MessageCodec, flutter_plugin1_message_codec, FLUTTER_PLUGIN1, MESSAGE_CODEC, FlStandardMessageCodec)

G_DECLARE_FINAL_TYPE(FlutterPlugin1MyHostApi, flutter_plugin1_my_host_api, FLUTTER_PLUGIN1, MY_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(FlutterPlugin1MyHostApiDoThingResponse, flutter_plugin1_my_host_api_do_thing_response, FLUTTER_PLUGIN1, MY_HOST_API_DO_THING_RESPONSE, GObject)

/**
 * flutter_plugin1_my_host_api_do_thing_response_new:
 *
 * Creates a new response to MyHostApi.doThing.
 *
 * Returns: a new #FlutterPlugin1MyHostApiDoThingResponse
 */
FlutterPlugin1MyHostApiDoThingResponse* flutter_plugin1_my_host_api_do_thing_response_new(FlValue* return_value);

/**
 * flutter_plugin1_my_host_api_do_thing_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to MyHostApi.doThing.
 *
 * Returns: a new #FlutterPlugin1MyHostApiDoThingResponse
 */
FlutterPlugin1MyHostApiDoThingResponse* flutter_plugin1_my_host_api_do_thing_response_new_error(const gchar* code, const gchar* message, FlValue* details);

/**
 * FlutterPlugin1MyHostApiVTable:
 *
 * Table of functions exposed by MyHostApi to be implemented by the API provider.
 */
typedef struct {
  FlutterPlugin1MyHostApiDoThingResponse* (*do_thing)(int64_t my_number, gpointer user_data);
} FlutterPlugin1MyHostApiVTable;

/**
 * flutter_plugin1_my_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the MyHostApi API.
 */
void flutter_plugin1_my_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const FlutterPlugin1MyHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * flutter_plugin1_my_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the MyHostApi API.
 */
void flutter_plugin1_my_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

G_END_DECLS

#endif  // PIGEON_MESSAGES_G_H_
